services:
  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: tada
      POSTGRES_USER: tadauser
      POSTGRES_PASSWORD: tadapw
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings

volumes:
  postgres_data:
