# Generated by Django 6.0.1 on 2026-02-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cand',
            name='fruit_preference',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cand',
            name='likes_cars',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cand',
            name='likes_games',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cand',
            name='likes_guns',
            field=models.BooleanField(default=False),
        ),
    ]
