# Generated by Django 6.0.1 on 2026-02-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_cand_fruit_preference_cand_likes_cars_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cand',
            name='fruit_preference',
        ),
        migrations.RemoveField(
            model_name='cand',
            name='likes_cars',
        ),
        migrations.RemoveField(
            model_name='cand',
            name='likes_games',
        ),
        migrations.RemoveField(
            model_name='cand',
            name='likes_guns',
        ),
        migrations.RemoveField(
            model_name='cand',
            name='phone',
        ),
        migrations.AddField(
            model_name='cand',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='cand',
            name='resume_url',
            field=models.URLField(blank=True),
        ),
    ]
