# Generated by Django 6.0.2 on 2026-02-20 05:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=80)),
                ('last_name', models.CharField(blank=True, max_length=80)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('bio', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField()),
                ('label', models.CharField(max_length=120)),
                ('strength_1_to_10', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='base.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff', to='base.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_staff', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IntakeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('new', 'New'), ('needs_email', 'Needs Email'), ('resolved', 'Resolved'), ('discarded', 'Discarded')], db_index=True, default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intake_submissions', to='base.company')),
                ('resolved_candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_submissions', to='base.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_global', models.BooleanField(db_index=True, default=False)),
                ('audience', models.CharField(choices=[('candidate', 'Candidate'), ('admin', 'Admin')], db_index=True, default='candidate', max_length=20)),
                ('question_type', models.CharField(choices=[('rating', 'Rating'), ('yesno', 'Yes/No'), ('text', 'Text'), ('single', 'Single choice'), ('multi', 'Multi choice')], db_index=True, default='rating', max_length=20)),
                ('prompt', models.TextField()),
                ('help_text', models.CharField(blank=True, max_length=240)),
                ('min_value', models.PositiveSmallIntegerField(default=1)),
                ('max_value', models.PositiveSmallIntegerField(default=10)),
                ('is_required', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='base.company')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_value', models.IntegerField(blank=True, null=True)),
                ('bool_value', models.BooleanField(blank=True, null=True)),
                ('text_value', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='base.candidate')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='base.question')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=140)),
                ('value', models.SlugField(max_length=140)),
                ('sort_order', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='base.question')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateAnswerChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multi_choices', to='base.candidateanswer')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multi_selected_in', to='base.questionchoice')),
            ],
        ),
        migrations.AddField(
            model_name='candidateanswer',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_in_answers', to='base.questionchoice'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['last_name', 'first_name'], name='base_candid_last_na_051688_idx'),
        ),
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.UniqueConstraint(fields=('email',), name='uniq_candidate_email'),
        ),
        migrations.AddConstraint(
            model_name='candidateinterest',
            constraint=models.UniqueConstraint(fields=('candidate', 'key'), name='uniq_candidate_interest_key'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['company', 'is_active', 'audience'], name='base_questi_company_e74543_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['is_global', 'is_active', 'audience'], name='base_questi_is_glob_161a53_idx'),
        ),
        migrations.AddConstraint(
            model_name='questionchoice',
            constraint=models.UniqueConstraint(fields=('question', 'value'), name='uniq_choice_value_per_question'),
        ),
        migrations.AddConstraint(
            model_name='candidateanswerchoice',
            constraint=models.UniqueConstraint(fields=('answer', 'choice'), name='uniq_answer_choice'),
        ),
        migrations.AddIndex(
            model_name='candidateanswer',
            index=models.Index(fields=['question'], name='base_candid_questio_afbf31_idx'),
        ),
        migrations.AddConstraint(
            model_name='candidateanswer',
            constraint=models.UniqueConstraint(fields=('candidate', 'question'), name='uniq_candidate_question_answer'),
        ),
    ]
