# Generated by Django 6.0.1 on 2026-03-30 10:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=40)),
                ('linkedin_url', models.URLField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_tokens', to='base.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('strength_1_to_10', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='base.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_companies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff', to='base.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_staff', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_notes', to=settings.AUTH_USER_MODEL)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='base.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('internship', 'Internship'), ('temporary', 'Temporary')], default='full_time', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='base.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_positions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('question_type', models.CharField(choices=[('rating', 'Rating'), ('yesno', 'Yes/No'), ('text', 'Text'), ('single', 'Single choice'), ('multi', 'Multi choice')], default='rating', max_length=20)),
                ('prompt', models.TextField()),
                ('help_text', models.CharField(blank=True, max_length=240)),
                ('is_required', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('page', models.PositiveSmallIntegerField(default=2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='base.company')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='base.position')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_value', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bool_value', models.BooleanField(blank=True, null=True)),
                ('text_value', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='base.question')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=140)),
                ('value', models.SlugField(max_length=140)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='base.question')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multi_choices', to='base.answer')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multi_selected_in', to='base.questionchoice')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_in_answers', to='base.questionchoice'),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('new', 'New'), ('discarded', 'Discarded'), ('finished', 'Finished')], default='new', max_length=20)),
                ('needs_claim', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='base.candidate')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='base.position')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='base.submission'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['email'], name='base_candid_email_8f0969_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['last_name', 'first_name'], name='base_candid_last_na_051688_idx'),
        ),
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.CheckConstraint(condition=models.Q(('email__contains', '@')), name='check_candidate_email'),
        ),
        migrations.AddConstraint(
            model_name='candidateinterest',
            constraint=models.UniqueConstraint(fields=('candidate', 'label'), name='uniq_candidate_interest_label'),
        ),
        migrations.AddConstraint(
            model_name='candidateinterest',
            constraint=models.CheckConstraint(condition=models.Q(('strength_1_to_10__gte', 1), ('strength_1_to_10__lte', 10)), name='check_interest_strength_1_to_10'),
        ),
        migrations.AddConstraint(
            model_name='companystaff',
            constraint=models.UniqueConstraint(fields=('user', 'company'), name='uniq_companystaff_user_company'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['company', 'is_active'], name='base_positi_company_065517_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['employment_type'], name='base_positi_employm_364912_idx'),
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.CheckConstraint(condition=models.Q(('employment_type__in', ['full_time', 'part_time', 'contract', 'internship', 'temporary'])), name='check_position_employment_type'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['question_type'], name='base_questi_questio_3ebdad_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['company', 'is_active'], name='base_questi_company_dc707e_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['position', 'is_active'], name='base_questi_positio_320216_idx'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(condition=models.Q(('question_type__in', ['rating', 'yesno', 'text', 'single', 'multi'])), name='check_question_type'),
        ),
        migrations.AddConstraint(
            model_name='questionchoice',
            constraint=models.UniqueConstraint(fields=('question', 'value'), name='uniq_choice_value_per_question'),
        ),
        migrations.AddConstraint(
            model_name='questionchoice',
            constraint=models.CheckConstraint(condition=models.Q(('sort_order__gte', 0)), name='check_questionchoice_sort_order'),
        ),
        migrations.AddConstraint(
            model_name='answerchoice',
            constraint=models.UniqueConstraint(fields=('answer', 'choice'), name='uniq_answer_choice'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['candidate', 'status'], name='base_submis_candida_2f9eb7_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['position', 'status'], name='base_submis_positio_c592e7_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['needs_claim'], name='base_submis_needs_c_3cf195_idx'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['new', 'discarded', 'finished'])), name='check_submission_status'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['question'], name='base_answer_questio_1ffb2c_idx'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('submission', 'question'), name='uniq_submission_question_answer'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.CheckConstraint(condition=models.Q(('int_value__isnull', True), ('int_value__gte', 0), _connector='OR'), name='check_answer_int_value'),
        ),
    ]
