# Generated by Django 6.0.1 on 2026-04-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='continue_code',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
