# Generated by Django 6.0.1 on 2026-03-01 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_candidate_admin_notes_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IntakeSubmission',
            new_name='Submission',
        ),
    ]
