# Generated by Django 6.0.1 on 2026-03-01 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_intakesubmission_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='email',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='resolved_candidate',
        ),
        migrations.AddField(
            model_name='submission',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='base.candidate'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('discarded', 'Discarded'), ('finished', 'Finished')], db_index=True, default='new', max_length=20),
        ),
    ]
