# Generated by Django 6.0.1 on 2026-03-02 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_submission_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
