# Generated by Django 6.0.1 on 2026-03-02 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_submission_finished_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='company',
        ),
        migrations.AddField(
            model_name='submission',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='base.position'),
        ),
    ]
