# Generated by Django 6.0.1 on 2026-03-02 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_submission_company_submission_position'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='question',
            name='base_questi_is_glob_161a53_idx',
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_global',
        ),
    ]
