# Generated by Django 6.0.1 on 2026-03-02 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_question_base_questi_is_glob_161a53_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='question',
            name='base_questi_company_e74543_idx',
        ),
        migrations.RemoveField(
            model_name='question',
            name='audience',
        ),
        migrations.RemoveField(
            model_name='question',
            name='max_value',
        ),
        migrations.RemoveField(
            model_name='question',
            name='min_value',
        ),
    ]
