# Generated by Django 6.0.1 on 2026-03-02 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_question_base_questi_company_e74543_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidateinterest',
            old_name='key',
            new_name='slug',
        ),
    ]
