# Generated by Django 6.0.1 on 2026-03-02 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_rename_key_candidateinterest_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_value', models.IntegerField(blank=True, null=True)),
                ('bool_value', models.BooleanField(blank=True, null=True)),
                ('text_value', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='candidateanswer',
            name='base_candid_questio_afbf31_idx',
        ),
        migrations.RemoveConstraint(
            model_name='candidateanswer',
            name='uniq_candidate_question_answer',
        ),
        migrations.RemoveConstraint(
            model_name='candidateinterest',
            name='uniq_candidate_interest_key',
        ),
        migrations.AlterField(
            model_name='question',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='base.position'),
        ),
        migrations.AddConstraint(
            model_name='candidateinterest',
            constraint=models.UniqueConstraint(fields=('candidate', 'slug'), name='uniq_candidate_interest_key'),
        ),
        migrations.RenameModel(
            old_name='CandidateAnswerChoice',
            new_name='AnswerChoice',
        ),
        migrations.AddField(
            model_name='answer',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_in_answers', to='base.questionchoice'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='base.question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='base.submission'),
        ),
        migrations.AlterField(
            model_name='answerchoice',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multi_choices', to='base.answer'),
        ),
        migrations.RemoveField(
            model_name='candidateanswer',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='candidateanswer',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='candidateanswer',
            name='question',
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['question'], name='base_answer_questio_1ffb2c_idx'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('submission', 'question'), name='uniq_submission_question_answer'),
        ),
        migrations.DeleteModel(
            name='CandidateAnswer',
        ),
    ]
