# Generated by Django 6.0.1 on 2026-03-06 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='base.candidate'),
        ),
    ]
