# Generated by Django 6.0.1 on 2026-03-08 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_submission_candidate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='candidate',
            name='uniq_candidate_email',
        ),
        migrations.RemoveConstraint(
            model_name='candidateinterest',
            name='uniq_candidate_interest_key',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='companystaff',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['email'], name='base_candid_email_8f0969_idx'),
        ),
        migrations.AddConstraint(
            model_name='candidateinterest',
            constraint=models.UniqueConstraint(fields=('candidate', 'label'), name='uniq_candidate_interest_label'),
        ),
        migrations.AddConstraint(
            model_name='companystaff',
            constraint=models.UniqueConstraint(fields=('user', 'company'), name='uniq_companystaff_user_company'),
        ),
        migrations.RemoveField(
            model_name='candidateinterest',
            name='slug',
        ),
    ]
