# Generated by Django 6.0.1 on 2026-03-09 02:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_remove_candidate_uniq_candidate_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='int_value',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateinterest',
            name='strength_1_to_10',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='position',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('internship', 'Internship'), ('temporary', 'Temporary')], db_index=True, default='full_time', max_length=20),
        ),
        migrations.AlterField(
            model_name='questionchoice',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.CheckConstraint(condition=models.Q(('int_value__isnull', True), ('int_value__gte', 0), _connector='OR'), name='check_answer_int_value'),
        ),
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.CheckConstraint(condition=models.Q(('email__contains', '@')), name='check_candidate_email'),
        ),
        migrations.AddConstraint(
            model_name='candidateinterest',
            constraint=models.CheckConstraint(condition=models.Q(('strength_1_to_10__gte', 1), ('strength_1_to_10__lte', 10)), name='check_interest_strength_1_to_10'),
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.CheckConstraint(condition=models.Q(('employment_type__in', ['full_time', 'part_time', 'contract', 'internship', 'temporary'])), name='check_position_employment_type'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(condition=models.Q(('question_type__in', ['rating', 'yesno', 'text', 'single', 'multi'])), name='check_question_type'),
        ),
        migrations.AddConstraint(
            model_name='questionchoice',
            constraint=models.CheckConstraint(condition=models.Q(('sort_order__gte', 0)), name='check_questionchoice_sort_order'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['new', 'discarded', 'finished'])), name='check_submission_status'),
        ),
    ]
