# Generated by Django 6.0.1 on 2026-03-21 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_candidate_first_name_alter_candidate_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='page',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
