# Generated by Django 6.0.1 on 2026-03-27 05:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_question_page'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='position',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('internship', 'Internship'), ('temporary', 'Temporary')], default='full_time', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('rating', 'Rating'), ('yesno', 'Yes/No'), ('text', 'Text'), ('single', 'Single choice'), ('multi', 'Multi choice')], default='rating', max_length=20),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('discarded', 'Discarded'), ('finished', 'Finished')], default='new', max_length=20),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['company', 'is_active'], name='base_positi_company_065517_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['employment_type'], name='base_positi_employm_364912_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['question_type'], name='base_questi_questio_3ebdad_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['company', 'is_active'], name='base_questi_company_dc707e_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['position', 'is_active'], name='base_questi_positio_320216_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['candidate', 'status'], name='base_submis_candida_2f9eb7_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['position', 'status'], name='base_submis_positio_c592e7_idx'),
        ),
    ]
