# Generated by Django 6.0.1 on 2026-03-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_candidate_email_alter_position_employment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='needs_claim',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['needs_claim'], name='base_submis_needs_c_3cf195_idx'),
        ),
    ]
